/**
 * Canonical Realtime Registry (Architecture §6).
 * Schema contract: every shared-state business event must have a row.
 * Wire names: see realtime.events.ts. FE synchronizers own Consistency Groups.
 */
import { RealtimeEvents, type RealtimeEventName } from './realtime.events';

export type RealtimeRoomKind = 'company' | 'user' | 'master-data';

export type CanonicalRealtimeRegistryRow = {
  businessEvent: string;
  wireEvent: RealtimeEventName;
  producer: string;
  rooms: RealtimeRoomKind[];
  consumers: string;
  cacheSynchronizer: string;
  consistencyGroup: string;
};

/** Canonical registry — one row family per Matrix / Architecture shared-state event. */
export const CANONICAL_REALTIME_REGISTRY: CanonicalRealtimeRegistryRow[] = [
  {
    businessEvent: 'InboundCreated/Updated',
    wireEvent: RealtimeEvents.INBOUND_ORDER_UPDATED,
    producer: 'inbound.service',
    rooms: ['company'],
    consumers: 'Admin inbound; Client inbound; dashboards',
    cacheSynchronizer: 'patchInbound* / client orders-cache + invalidateClientDashboard',
    consistencyGroup: 'Matrix §3.2',
  },
  {
    businessEvent: 'OutboundCreated/Updated',
    wireEvent: RealtimeEvents.OUTBOUND_ORDER_UPDATED,
    producer: 'outbound.service',
    rooms: ['company'],
    consumers: 'Admin outbound; Client outbound; dashboards',
    cacheSynchronizer: 'patchOutbound* / client orders-cache + invalidateClientDashboard',
    consistencyGroup: 'Matrix §3.3',
  },
  {
    businessEvent: 'Oms*',
    wireEvent: RealtimeEvents.OMS_ORDER_EVENT,
    producer: 'oms-orders.service',
    rooms: ['company'],
    consumers: 'Admin OMS; Client ecommerce; COD; dashboards',
    cacheSynchronizer: 'invalidate OMS keys + invalidateClientDashboard',
    consistencyGroup: 'Matrix §3.4',
  },
  {
    businessEvent: 'StockChanged',
    wireEvent: RealtimeEvents.INVENTORY_CHANGED,
    producer: 'inbound/outbound/adjustments/tasks/returns/inventory',
    rooms: ['company'],
    consumers: 'Admin inventory; Client stock/products; dashboards',
    cacheSynchronizer: 'patchInventoryChanged / patchClientStock + invalidateClientDashboard',
    consistencyGroup: 'Matrix §3.5',
  },
  {
    businessEvent: 'Task*',
    wireEvent: RealtimeEvents.TASK_UPDATED,
    producer: 'warehouse-tasks.service',
    rooms: ['company'],
    consumers: 'Admin tasks; order stages',
    cacheSynchronizer: 'patchTaskUpdated',
    consistencyGroup: 'Matrix §3.6',
  },
  {
    businessEvent: 'WmsReturn*',
    wireEvent: RealtimeEvents.RETURN_UPDATED,
    producer: 'returns.service',
    rooms: ['company'],
    consumers: 'Admin returns; Client returns',
    cacheSynchronizer: 'patchReturn* / client returns sync',
    consistencyGroup: 'Matrix §3.8',
  },
  {
    businessEvent: 'OmsReturn*',
    wireEvent: RealtimeEvents.OMS_RETURN_EVENT,
    producer: 'oms-returns.service',
    rooms: ['company'],
    consumers: 'Admin OMS returns; Client ecommerce returns',
    cacheSynchronizer: 'invalidate oms-returns + client returns',
    consistencyGroup: 'Matrix §3.8',
  },
  {
    businessEvent: 'CompanyLifecycle',
    wireEvent: RealtimeEvents.COMPANY_LIFECYCLE_CHANGED,
    producer: 'customer-lifecycle.service',
    rooms: ['company', 'master-data'],
    consumers: 'Admin clients; Client portal gate',
    cacheSynchronizer: 'clients + operational access + dashboard',
    consistencyGroup: 'Matrix §3.1',
  },
  {
    businessEvent: 'BillingRestricted*',
    wireEvent: RealtimeEvents.BILLING_RESTRICTION_CHANGED,
    producer: 'billing-cycle-processor / billing-access',
    rooms: ['company'],
    consumers: 'Client restriction banner; Admin billing widgets',
    cacheSynchronizer: 'operational access + billing queries',
    consistencyGroup: 'Matrix §3.1 / §3.9',
  },
  {
    businessEvent: 'Cod*',
    wireEvent: RealtimeEvents.COD_UPDATED,
    producer: 'cod-records.service',
    rooms: ['company'],
    consumers: 'Admin COD; Client my-profits; dashboards',
    cacheSynchronizer: 'cod-report + invalidateClientDashboard',
    consistencyGroup: 'Matrix §3.4 COD',
  },
  {
    businessEvent: 'Notification*',
    wireEvent: RealtimeEvents.NOTIFICATION_CREATED,
    producer: 'notifications / client-notifications / billing-notifications',
    rooms: ['user'],
    consumers: 'Bell + inbox both portals',
    cacheSynchronizer: 'patchNotification*',
    consistencyGroup: 'Matrix §3.7',
  },
  {
    businessEvent: 'NotificationRead/Deleted',
    wireEvent: RealtimeEvents.NOTIFICATION_DELETED,
    producer: 'notifications.service',
    rooms: ['user'],
    consumers: 'Admin + Client notification inbox',
    cacheSynchronizer: 'patchNotificationRead / deleted invalidate',
    consistencyGroup: 'Matrix §3.7',
  },
  {
    businessEvent: 'AuthSession*',
    wireEvent: RealtimeEvents.AUTH_SESSION_CHANGED,
    producer: 'auth.service / users.service / customer-lifecycle',
    rooms: ['user', 'master-data'],
    consumers: 'AuthContext admin + client',
    cacheSynchronizer: 'force logout / session clear',
    consistencyGroup: 'SameUser session',
  },
  {
    businessEvent: 'DocumentGenerated',
    wireEvent: RealtimeEvents.DOCUMENT_GENERATED,
    producer: 'grn/dn/final-contract pdf services',
    rooms: ['company', 'master-data'],
    consumers: 'Admin documents panels; contracts catalogs',
    cacheSynchronizer: 'invalidate documents + contracts keys',
    consistencyGroup: 'Matrix §3.10 Documents',
  },
  {
    businessEvent: 'DocumentSlotOverrideChanged',
    wireEvent: RealtimeEvents.DOCUMENT_SLOT_OVERRIDE_CHANGED,
    producer: 'document-slot-overrides.service',
    rooms: ['company', 'master-data'],
    consumers: 'Admin task/order document panels',
    cacheSynchronizer: 'invalidate documents + tasks',
    consistencyGroup: 'Matrix §3.10 Documents',
  },
  {
    businessEvent: 'FinalContractCreated/Updated',
    wireEvent: RealtimeEvents.FINAL_CONTRACT_CHANGED,
    producer: 'final-contracts.service',
    rooms: ['master-data', 'company'],
    consumers: 'Admin /contracts/final-contract',
    cacheSynchronizer: 'invalidate QK.contractsFinalContract',
    consistencyGroup: 'Matrix §3.10 Contracts',
  },
  {
    businessEvent: 'FormSubmitted',
    wireEvent: RealtimeEvents.FORM_SUBMITTED,
    producer: 'forms.service',
    rooms: ['master-data'],
    consumers: 'Admin /forms inbox',
    cacheSynchronizer: 'invalidate QK.forms.*',
    consistencyGroup: 'Matrix Forms',
  },
  {
    businessEvent: 'Invoice*',
    wireEvent: RealtimeEvents.INVOICE_UPDATED,
    producer: 'billing-invoices / cycle-processor',
    rooms: ['company', 'master-data'],
    consumers: 'Admin billing; Client /billing /invoices',
    cacheSynchronizer: 'invalidate billing invoice keys both portals',
    consistencyGroup: 'Matrix §3.9 Billing',
  },
  {
    businessEvent: 'Plan* / CapacityChanged',
    wireEvent: RealtimeEvents.PLAN_UPDATED,
    producer: 'billing-plans.service',
    rooms: ['company', 'master-data'],
    consumers: 'Admin plans/capacity; Client billing summary',
    cacheSynchronizer: 'invalidate billing plan + capacity keys',
    consistencyGroup: 'Matrix §3.9 Billing',
  },
  {
    businessEvent: 'BackupJob*',
    wireEvent: RealtimeEvents.BACKUP_JOB_PROGRESS,
    producer: 'backup-runner / restore-runner',
    rooms: ['master-data'],
    consumers: 'Admin backups UI (super_admin)',
    cacheSynchronizer: 'patch backup status + invalidate list/ops',
    consistencyGroup: 'Matrix Backups',
  },
  {
    businessEvent: 'Product*',
    wireEvent: RealtimeEvents.PRODUCT_UPDATED,
    producer: 'products.service',
    rooms: ['company'],
    consumers: 'Admin products; Client products',
    cacheSynchronizer: 'patchProduct* / client products-cache',
    consistencyGroup: 'Matrix Products',
  },
  {
    businessEvent: 'User*',
    wireEvent: RealtimeEvents.USER_UPDATED,
    producer: 'users.service',
    rooms: ['master-data', 'company'],
    consumers: 'Admin users list',
    cacheSynchronizer: 'patchUser*',
    consistencyGroup: 'Matrix Users',
  },
  {
    businessEvent: 'Warehouse*',
    wireEvent: RealtimeEvents.WAREHOUSE_UPDATED,
    producer: 'warehouses.service',
    rooms: ['master-data'],
    consumers: 'Admin warehouses',
    cacheSynchronizer: 'patchWarehouse*',
    consistencyGroup: 'Matrix Warehouses',
  },
  {
    businessEvent: 'Location*',
    wireEvent: RealtimeEvents.LOCATION_UPDATED,
    producer: 'locations.service',
    rooms: ['master-data'],
    consumers: 'Admin locations',
    cacheSynchronizer: 'patchLocation*',
    consistencyGroup: 'Matrix Locations',
  },
  {
    businessEvent: 'CycleCount*',
    wireEvent: RealtimeEvents.CYCLE_COUNT_UPDATED,
    producer: 'cycle-count.service',
    rooms: ['company'],
    consumers: 'Admin cycle count lists/detail/my-tasks',
    cacheSynchronizer: 'patchCycleCount*',
    consistencyGroup: 'Matrix Cycle Count',
  },
  {
    businessEvent: 'CycleCountPosted→Stock',
    wireEvent: RealtimeEvents.INVENTORY_CHANGED,
    producer: 'cycle-count-variance.postReconciliation → adjustments.approve',
    rooms: ['company'],
    consumers: 'Admin inventory; Client stock',
    cacheSynchronizer: 'patchInventoryChanged (per productId)',
    consistencyGroup: 'Matrix §3.5 / G-STOCK-03',
  },
  {
    businessEvent: 'AdjustmentCreated/Approved',
    wireEvent: RealtimeEvents.ADJUSTMENT_APPROVED,
    producer: 'adjustments.service / cycle-count-variance draft',
    rooms: ['company'],
    consumers: 'Admin adjustments',
    cacheSynchronizer: 'patchAdjustment*',
    consistencyGroup: 'Matrix Adjustments',
  },
  {
    businessEvent: 'InternalTransferCompleted',
    wireEvent: RealtimeEvents.TRANSFER_COMPLETED,
    producer: 'inventory.service',
    rooms: ['company'],
    consumers: 'Admin internal transfer / ledger',
    cacheSynchronizer: 'patchTransferCompleted (created is intentional no-op)',
    consistencyGroup: 'Matrix Transfers / G-TR-01',
  },
  {
    businessEvent: 'AuditLogCreated',
    wireEvent: RealtimeEvents.AUDIT_LOG_CREATED,
    producer: 'audit-log.service',
    rooms: ['master-data', 'company'],
    consumers: 'Admin audit logs',
    cacheSynchronizer: 'patchAuditLogCreated',
    consistencyGroup: 'Matrix Audit',
  },
  {
    businessEvent: 'Dashboard*',
    wireEvent: RealtimeEvents.DASHBOARD_ORDERS_UPDATED,
    producer: 'realtime.service scheduleDashboard → dashboard-realtime',
    rooms: ['master-data'],
    consumers: 'Admin dashboard overview',
    cacheSynchronizer: 'patchDashboard*',
    consistencyGroup: 'Matrix Dashboards / G-DASH-01',
  },
  {
    businessEvent: 'Presence*',
    wireEvent: RealtimeEvents.PRESENCE_ONLINE,
    producer: 'presence.service',
    rooms: ['master-data'],
    consumers: 'Admin presence indicators',
    cacheSynchronizer: 'patchPresence*',
    consistencyGroup: 'Presence (platform)',
  },
];
