import { Type } from 'class-transformer';
import {
  ArrayMinSize,
  IsArray,
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsPositive,
  IsString,
  Matches,
  MaxLength,
  ValidateIf,
  ValidateNested,
} from 'class-validator';

export class ExternalOutboundLineDto {
  @IsString()
  @IsNotEmpty({ message: 'Product SKU is required.' })
  @MaxLength(80)
  sku!: string;

  @Type(() => Number)
  @IsInt({ message: 'Quantity must be a whole number (no decimals).' })
  @IsPositive({ message: 'Quantity must be a positive whole number.' })
  quantity!: number;
}

/**
 * External outbound create — mirrors Client Portal /outbound-orders/new
 * plus optional-but-required-for-API customer reference `externalOrderId`.
 * Internal order number / id / status are generated by the system.
 */
export class ExternalCreateOutboundOrderDto {
  /** Customer reference (not our internal order id). */
  @IsString()
  @IsNotEmpty({ message: 'externalOrderId is required.' })
  @MaxLength(80)
  @Matches(/^[A-Za-z0-9-]+$/, {
    message:
      'externalOrderId may only contain English letters, English digits (0-9), and hyphen (-).',
  })
  externalOrderId!: string;

  /**
   * Destination text (same as Create page "Destination").
   * Prefer this field; legacy clients may send `destinationAddress` instead.
   */
  @ValidateIf((o: ExternalCreateOutboundOrderDto) => !String(o.destinationAddress ?? '').trim())
  @IsString()
  @IsNotEmpty({ message: 'destination is required.' })
  @MaxLength(400)
  destination?: string;

  /** @deprecated Prefer `destination`. Kept for backward-compatible payloads. */
  @IsOptional()
  @IsString()
  @MaxLength(400)
  destinationAddress?: string;

  /** YYYY-MM-DD or M/DD/YYYY (English digits). */
  @IsString()
  @IsNotEmpty({ message: 'requiredShipDate is required.' })
  requiredShipDate!: string;

  @IsOptional()
  @IsString()
  @MaxLength(80)
  carrier?: string;

  @IsOptional()
  @IsString()
  @MaxLength(2000)
  notes?: string;

  @IsArray()
  @ArrayMinSize(1, { message: 'Add at least one product line.' })
  @ValidateNested({ each: true })
  @Type(() => ExternalOutboundLineDto)
  lines!: ExternalOutboundLineDto[];
}
