import { Type } from 'class-transformer';
import {
  ArrayMinSize,
  IsArray,
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsPositive,
  IsString,
  Matches,
  MaxLength,
  ValidateNested,
} from 'class-validator';

export class ExternalInboundLineDto {
  @IsString()
  @IsNotEmpty({ message: 'Product SKU is required.' })
  @MaxLength(80)
  sku!: string;

  @Type(() => Number)
  @IsInt({ message: 'Quantity must be a whole number (no decimals).' })
  @IsPositive({ message: 'Quantity must be a positive whole number.' })
  quantity!: number;
}

/**
 * External inbound create — mirrors Client Portal /inbound-orders/new
 * plus optional customer reference `externalOrderId` for integration.
 * Internal order number / id / status are generated by the system.
 */
export class ExternalCreateInboundOrderDto {
  /** Customer reference (not our internal order id). */
  @IsString()
  @IsNotEmpty({ message: 'externalOrderId is required.' })
  @MaxLength(80)
  @Matches(/^[A-Za-z0-9-]+$/, {
    message:
      'externalOrderId may only contain English letters, English digits (0-9), and hyphen (-).',
  })
  externalOrderId!: string;

  /** YYYY-MM-DD or M/DD/YYYY (English digits). */
  @IsString()
  @IsNotEmpty({ message: 'expectedArrivalDate is required.' })
  expectedArrivalDate!: string;

  @IsOptional()
  @IsString()
  @MaxLength(2000)
  notes?: string;

  @IsArray()
  @ArrayMinSize(1, { message: 'Add at least one product line.' })
  @ValidateNested({ each: true })
  @Type(() => ExternalInboundLineDto)
  lines!: ExternalInboundLineDto[];
}
