import { col } from './column-helpers';
import { getCatalogEntry } from './report-catalog';
import type { ReportDefinition } from './types';

const MOVEMENT_TYPES = [
  { value: 'inbound', label: 'Inbound', labelAr: 'وارد' },
  { value: 'outbound', label: 'Outbound', labelAr: 'صادر' },
  { value: 'adjustment', label: 'Adjustment', labelAr: 'تسوية' },
];

const STOCK_STATUS = [
  { value: 'available', label: 'Available', labelAr: 'متاح' },
  { value: 'quarantined', label: 'Quarantined', labelAr: 'حجر' },
  { value: 'awaiting_putaway', label: 'Awaiting putaway', labelAr: 'بانتظار التخزين' },
];

const STOCK_AGING_BUCKETS = [
  { value: 'No movement', label: 'No movement', labelAr: 'بدون حركة' },
  { value: '0–30 days', label: '0–30 days', labelAr: '0–30 يوم' },
  { value: '31–90 days', label: '31–90 days', labelAr: '31–90 يوم' },
  { value: '91–180 days', label: '91–180 days', labelAr: '91–180 يوم' },
  { value: '180+ days', label: '180+ days', labelAr: '180+ يوم' },
];

const LOT_EXPIRY_BUCKETS = [
  { value: 'No expiry', label: 'No expiry', labelAr: 'بدون انتهاء' },
  { value: 'Expired', label: 'Expired', labelAr: 'منتهي' },
  { value: '0–30 days', label: '0–30 days', labelAr: '0–30 يوم' },
  { value: '31–90 days', label: '31–90 days', labelAr: '31–90 يوم' },
  { value: '91–180 days', label: '91–180 days', labelAr: '91–180 يوم' },
  { value: '180+ days', label: '180+ days', labelAr: '180+ يوم' },
];

const INVOICE_STATUS = [
  { value: 'paid', label: 'Paid', labelAr: 'مدفوع' },
  { value: 'open', label: 'Open', labelAr: 'مفتوح' },
  { value: 'overdue', label: 'Overdue', labelAr: 'متأخر' },
];

const COD_STATUS = [
  { value: 'pending', label: 'Pending', labelAr: 'معلق' },
  { value: 'collected', label: 'Collected', labelAr: 'محصّل' },
  { value: 'remitted', label: 'Remitted', labelAr: 'مُحوّل' },
  { value: 'settled', label: 'Settled', labelAr: 'مسوّى' },
];

const ALLOCATION_STATUS = [
  { value: 'pending', label: 'Pending', labelAr: 'معلق' },
  { value: 'allocated', label: 'Allocated', labelAr: 'مخصّص' },
  { value: 'partial', label: 'Partial', labelAr: 'جزئي' },
  { value: 'released', label: 'Released', labelAr: 'مُحرّر' },
];

const RECEIVABLES_AGING_BUCKETS = [
  { value: 'Current', label: 'Current', labelAr: 'جاري' },
  { value: '1–30 days', label: '1–30 days', labelAr: '1–30 يوم' },
  { value: '31–60 days', label: '31–60 days', labelAr: '31–60 يوم' },
  { value: '61–90 days', label: '61–90 days', labelAr: '61–90 يوم' },
  { value: '90+ days', label: '90+ days', labelAr: '90+ يوم' },
];

const TASK_TYPE_FILTER = [
  { value: 'receiving', label: 'Receiving', labelAr: 'استلام' },
  { value: 'putaway', label: 'Putaway', labelAr: 'تخزين' },
  { value: 'pick', label: 'Pick', labelAr: 'التقاط' },
  { value: 'pack', label: 'Pack', labelAr: 'تغليف' },
  { value: 'dispatch', label: 'Dispatch', labelAr: 'تسليم' },
];


function catalogMeta(id: ReportDefinition['id']) {
  const entry = getCatalogEntry(id)!;
  return {
    title: entry.title,
    titleAr: entry.titleAr,
    description: entry.description,
    descriptionAr: entry.descriptionAr,
  };
}

export const REPORT_REGISTRY: ReportDefinition[] = [
  {
    id: 'warehouse-analysis',
    ...catalogMeta('warehouse-analysis'),
    columns: [
      col('week', 'Week', 'الأسبوع', { sortable: true }),
      col('inboundCount', 'Inbound', 'وارد', { sortable: true, className: 'text-end' }),
      col('outboundCount', 'Outbound', 'صادر', { sortable: true, className: 'text-end' }),
      col('totalCount', 'Total', 'الإجمالي', { sortable: true, className: 'text-end' }),
    ],
    filterKeys: ['warehouse', 'client', 'dateRange'],
    defaultView: 'graph',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'line',
    chartLabelKey: 'week',
    chartValueKey: 'totalCount',
    exportFileName: 'warehouse-analysis',
    serverSide: true,
    loadsWarehouseKpis: true,
  },
  {
    id: 'inventory',
    ...catalogMeta('inventory'),
    columns: [
      col('sku', 'SKU', 'رمز الصنف', { sortable: true }),
      col('product', 'Product', 'المنتج', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('location', 'Location', 'الموقع', { sortable: true }),
      col('lot', 'Lot', 'الدفعة'),
      col('expiry', 'Expiry', 'الانتهاء'),
      col('onHand', 'On hand', 'في المخزون', { sortable: true }),
      col('reserved', 'Reserved', 'محجوز', { sortable: true }),
      col('available', 'Available', 'متاح', { sortable: true }),
      col('stockStatus', 'Status', 'الحالة', { sortable: true }),
      col('uom', 'UoM', 'وحدة'),
      col('warehouse', 'Warehouse', 'المستودع'),
    ],
    filterKeys: ['warehouse', 'client', 'sku', 'status'],
    statusOptions: STOCK_STATUS,
    groupByOptions: [
      { value: 'client', label: 'Client', labelAr: 'العميل' },
      { value: 'location', label: 'Location', labelAr: 'الموقع' },
      { value: 'stockStatus', label: 'Status', labelAr: 'الحالة' },
    ],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'client',
    chartValueKey: 'onHand',
    exportFileName: 'inventory',
    serverSide: true,
  },
  {
    id: 'product-moves',
    ...catalogMeta('product-moves'),
    columns: [
      col('date', 'Date', 'التاريخ', { sortable: true }),
      col('product', 'Product', 'المنتج', { sortable: true }),
      col('sku', 'SKU', 'رمز الصنف', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('movement', 'Movement', 'الحركة', { sortable: true }),
      col('status', 'Status', 'الحالة'),
      col('quantity', 'Qty', 'الكمية', { sortable: true }),
      col('reference', 'Reference', 'المرجع'),
      col('operator', 'Operator', 'المشغّل', { sortable: true }),
      col('lot', 'Lot', 'الدفعة'),
      col('fromLocation', 'From', 'من'),
      col('toLocation', 'To', 'إلى'),
    ],
    filterKeys: ['warehouse', 'client', 'sku', 'status', 'dateRange', 'groupBy'],
    statusOptions: MOVEMENT_TYPES,
    groupByOptions: [
      { value: 'movement', label: 'Movement type', labelAr: 'نوع الحركة' },
      { value: 'client', label: 'Client', labelAr: 'العميل' },
      { value: 'sku', label: 'SKU', labelAr: 'رمز الصنف' },
    ],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'line',
    chartLabelKey: 'date',
    chartValueKey: 'quantity',
    exportFileName: 'product-moves',
    serverSide: true,
  },
  {
    id: 'stock-aging',
    ...catalogMeta('stock-aging'),
    columns: [
      col('sku', 'SKU', 'رمز الصنف', { sortable: true }),
      col('product', 'Product', 'المنتج', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('location', 'Location', 'الموقع', { sortable: true }),
      col('lastMovement', 'Last movement', 'آخر حركة', { sortable: true }),
      col('daysSinceMovement', 'Days idle', 'أيام بدون حركة', { sortable: true, className: 'text-end' }),
      col('agingBucket', 'Aging bucket', 'فئة التقادم', { sortable: true }),
      col('onHand', 'On hand', 'في المخزون', { sortable: true, className: 'text-end' }),
      col('stagnant', 'Stagnant', 'راكد', { sortable: true }),
    ],
    filterKeys: ['warehouse', 'client', 'sku', 'status'],
    statusOptions: STOCK_AGING_BUCKETS,
    groupByOptions: [
      { value: 'agingBucket', label: 'Aging bucket', labelAr: 'فئة التقادم' },
      { value: 'client', label: 'Client', labelAr: 'العميل' },
    ],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'agingBucket',
    chartValueKey: 'onHand',
    exportFileName: 'stock-aging',
    serverSide: true,
  },
  {
    id: 'lot-expiry',
    ...catalogMeta('lot-expiry'),
    columns: [
      col('sku', 'SKU', 'رمز الصنف', { sortable: true }),
      col('product', 'Product', 'المنتج', { sortable: true }),
      col('lot', 'Lot', 'الدفعة', { sortable: true }),
      col('expiry', 'Expiry', 'الانتهاء', { sortable: true }),
      col('daysUntil', 'Days until', 'أيام متبقية', { sortable: true, className: 'text-end' }),
      col('agingBucket', 'Expiry bucket', 'فئة الانتهاء', { sortable: true }),
      col('location', 'Location', 'الموقع', { sortable: true }),
      col('quantity', 'Qty', 'الكمية', { sortable: true, className: 'text-end' }),
    ],
    filterKeys: ['warehouse', 'client', 'sku', 'status'],
    statusOptions: LOT_EXPIRY_BUCKETS,
    groupByOptions: [
      { value: 'agingBucket', label: 'Expiry bucket', labelAr: 'فئة الانتهاء' },
      { value: 'sku', label: 'SKU', labelAr: 'رمز الصنف' },
    ],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'agingBucket',
    chartValueKey: 'quantity',
    exportFileName: 'lot-expiry',
    serverSide: true,
  },
  {
    id: 'capacity-utilization',
    ...catalogMeta('capacity-utilization'),
    columns: [
      col('location', 'Location', 'الموقع', { sortable: true }),
      col('type', 'Type', 'النوع', { sortable: true }),
      col('skuCount', 'SKUs', 'أصناف', { sortable: true, className: 'text-end' }),
      col('totalQty', 'Total qty', 'الكمية', { sortable: true, className: 'text-end' }),
      col('utilization', 'Utilization', 'الاستخدام', { sortable: true }),
    ],
    filterKeys: ['warehouse', 'client', 'sku'],
    groupByOptions: [{ value: 'type', label: 'Location type', labelAr: 'نوع الموقع' }],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'location',
    chartValueKey: 'totalQty',
    exportFileName: 'capacity-utilization',
    serverSide: true,
  },
  {
    id: 'return-rate',
    ...catalogMeta('return-rate'),
    columns: [
      col('client', 'Client', 'العميل', { sortable: true }),
      col('outboundOrders', 'Outbound', 'صادر', { sortable: true, className: 'text-end' }),
      col('returnOrders', 'Returns', 'مرتجعات', { sortable: true, className: 'text-end' }),
      col('returnRatePercent', 'Return rate', 'معدل الإرجاع', { sortable: true, className: 'text-end' }),
    ],
    filterKeys: ['warehouse', 'client', 'dateRange'],
    groupByOptions: [{ value: 'client', label: 'Client', labelAr: 'العميل' }],
    defaultView: 'graph',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'client',
    chartValueKey: 'returnRatePercent',
    exportFileName: 'return-rate',
    serverSide: true,
  },
  {
    id: 'worker-productivity',
    ...catalogMeta('worker-productivity'),
    columns: [
      col('worker', 'Worker', 'العامل', { sortable: true }),
      col('completedTasks', 'Completed', 'مكتمل', { sortable: true, className: 'text-end' }),
      col('taskTypes', 'Task types', 'أنواع المهام'),
      col('avgCycleHours', 'Avg cycle (h)', 'متوسط الدورة (س)', { sortable: true, className: 'text-end' }),
      col('pickPackCount', 'Pick/pack', 'التقاط/تغليف', { sortable: true, className: 'text-end' }),
    ],
    filterKeys: ['warehouse', 'client', 'dateRange', 'status'],
    statusOptions: TASK_TYPE_FILTER,
    groupByOptions: [
      { value: 'taskTypes', label: 'Task types', labelAr: 'أنواع المهام' },
    ],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'worker',
    chartValueKey: 'completedTasks',
    exportFileName: 'worker-productivity',
    serverSide: true,
  },
  {
    id: 'order-cycle-time',
    ...catalogMeta('order-cycle-time'),
    columns: [
      col('orderType', 'Type', 'النوع', { sortable: true }),
      col('orderNumber', 'Order #', 'رقم الطلب', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('status', 'Status', 'الحالة', { sortable: true }),
      col('cycleHours', 'Cycle (h)', 'الدورة (س)', { sortable: true, className: 'text-end' }),
      col('milestoneStart', 'Start', 'البداية'),
      col('milestoneEnd', 'End', 'النهاية'),
    ],
    filterKeys: ['warehouse', 'client', 'dateRange'],
    groupByOptions: [
      { value: 'orderType', label: 'Order type', labelAr: 'نوع الطلب' },
      { value: 'client', label: 'Client', labelAr: 'العميل' },
    ],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'orderNumber',
    chartValueKey: 'cycleHours',
    exportFileName: 'order-cycle-time',
    serverSide: true,
  },
  {
    id: 'inbound-accuracy',
    ...catalogMeta('inbound-accuracy'),
    columns: [
      col('orderNumber', 'Order #', 'رقم الطلب', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('status', 'Status', 'الحالة', { sortable: true }),
      col('lineCount', 'Lines', 'الأسطر', { sortable: true, className: 'text-end' }),
      col('discrepancyLines', 'Discrepancies', 'فروقات', { sortable: true, className: 'text-end' }),
      col('accuracyPercent', 'Accuracy', 'الدقة', { sortable: true, className: 'text-end' }),
      col('receivedVsExpected', 'Recv/exp', 'مستلم/متوقع'),
    ],
    filterKeys: ['warehouse', 'client', 'dateRange'],
    groupByOptions: [{ value: 'client', label: 'Client', labelAr: 'العميل' }],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'client',
    chartValueKey: 'accuracyPercent',
    exportFileName: 'inbound-accuracy',
    serverSide: true,
  },
  {
    id: 'outbound-fill-rate',
    ...catalogMeta('outbound-fill-rate'),
    columns: [
      col('orderNumber', 'Order #', 'رقم الطلب', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('status', 'Status', 'الحالة', { sortable: true }),
      col('requestedQty', 'Requested', 'مطلوب', { sortable: true, className: 'text-end' }),
      col('pickedQty', 'Picked', 'ملتقط', { sortable: true, className: 'text-end' }),
      col('fillRatePercent', 'Fill rate', 'معدل التعبئة', { sortable: true, className: 'text-end' }),
      col('shortShip', 'Short ship', 'نقص', { sortable: true }),
    ],
    filterKeys: ['warehouse', 'client', 'dateRange'],
    groupByOptions: [{ value: 'client', label: 'Client', labelAr: 'العميل' }],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'client',
    chartValueKey: 'fillRatePercent',
    exportFileName: 'outbound-fill-rate',
    serverSide: true,
  },
  {
    id: 'sla-compliance',
    ...catalogMeta('sla-compliance'),
    columns: [
      col('taskType', 'Task type', 'نوع المهمة', { sortable: true }),
      col('totalTasks', 'Total', 'الإجمالي', { sortable: true, className: 'text-end' }),
      col('onTimeTasks', 'On time', 'في الوقت', { sortable: true, className: 'text-end' }),
      col('breachedTasks', 'Breached', 'متأخر', { sortable: true, className: 'text-end' }),
      col('escalatedTasks', 'Escalated', 'مُصعَّد', { sortable: true, className: 'text-end' }),
      col('compliancePercent', 'Compliance', 'الالتزام', { sortable: true, className: 'text-end' }),
    ],
    filterKeys: ['warehouse', 'client', 'dateRange', 'status'],
    statusOptions: TASK_TYPE_FILTER,
    groupByOptions: [{ value: 'taskType', label: 'Task type', labelAr: 'نوع المهمة' }],
    defaultView: 'graph',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'taskType',
    chartValueKey: 'compliancePercent',
    exportFileName: 'sla-compliance',
    serverSide: true,
  },
  {
    id: 'revenue-by-client',
    ...catalogMeta('revenue-by-client'),
    columns: [
      col('client', 'Client', 'العميل', { sortable: true }),
      col('invoiceCount', 'Invoices', 'فواتير', { sortable: true, className: 'text-end' }),
      col('revenue', 'Revenue', 'الإيرادات', { sortable: true, className: 'text-end' }),
    ],
    filterKeys: ['client', 'dateRange', 'status'],
    statusOptions: INVOICE_STATUS,
    groupByOptions: [{ value: 'client', label: 'Client', labelAr: 'العميل' }],
    defaultView: 'graph',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'client',
    chartValueKey: 'revenue',
    exportFileName: 'revenue-by-client',
    serverSide: true,
  },
  {
    id: 'receivables-aging',
    ...catalogMeta('receivables-aging'),
    columns: [
      col('invoiceNumber', 'Invoice #', 'رقم الفاتورة', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('status', 'Status', 'الحالة', { sortable: true }),
      col('amount', 'Amount', 'المبلغ', { sortable: true, className: 'text-end' }),
      col('issuedAt', 'Issued', 'تاريخ الإصدار', { sortable: true }),
      col('dueDate', 'Due', 'تاريخ الاستحقاق', { sortable: true }),
      col('daysPastDue', 'Days past due', 'أيام التأخير', { sortable: true, className: 'text-end' }),
      col('agingBucket', 'Aging bucket', 'فئة العمر', { sortable: true }),
    ],
    filterKeys: ['client', 'status'],
    statusOptions: RECEIVABLES_AGING_BUCKETS,
    groupByOptions: [
      { value: 'agingBucket', label: 'Aging bucket', labelAr: 'فئة العمر' },
      { value: 'client', label: 'Client', labelAr: 'العميل' },
    ],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'agingBucket',
    chartValueKey: 'amount',
    exportFileName: 'receivables-aging',
    serverSide: true,
  },
  {
    id: 'cod-report',
    ...catalogMeta('cod-report'),
    columns: [
      col('orderNumber', 'Order #', 'رقم الطلب', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('recipient', 'Recipient', 'المستلم', { sortable: true }),
      col('codAmount', 'COD amount', 'مبلغ COD', { sortable: true, className: 'text-end' }),
      col('codStatus', 'COD status', 'حالة COD', { sortable: true }),
      col('currency', 'Currency', 'العملة'),
      col('collectedAt', 'Collected', 'تاريخ التحصيل', { sortable: true }),
      col('remittedAt', 'Remitted', 'تاريخ التحويل', { sortable: true }),
      col('orderStatus', 'Order status', 'حالة الطلب', { sortable: true }),
      col('createdAt', 'Created', 'تاريخ الإنشاء', { sortable: true }),
    ],
    filterKeys: ['client', 'dateRange', 'status'],
    statusOptions: COD_STATUS,
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'codStatus',
    chartValueKey: 'codAmount',
    exportFileName: 'cod-report',
    serverSide: true,
  },
  {
    id: 'merchant-orders',
    ...catalogMeta('merchant-orders'),
    columns: [
      col('orderNumber', 'Order #', 'رقم الطلب', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('status', 'Status', 'الحالة', { sortable: true }),
      col('recipient', 'Recipient', 'المستلم', { sortable: true }),
      col('city', 'City', 'المدينة', { sortable: true }),
      col('paymentMethod', 'Payment', 'الدفع', { sortable: true }),
      col('allocationStatus', 'Allocation', 'التخصيص', { sortable: true }),
      col('lineCount', 'Lines', 'البنود', { sortable: true, className: 'text-end' }),
      col('createdAt', 'Created', 'تاريخ الإنشاء', { sortable: true }),
    ],
    filterKeys: ['client', 'dateRange', 'status'],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'status',
    chartValueKey: 'lineCount',
    exportFileName: 'merchant-orders',
    serverSide: true,
  },
  {
    id: 'sales-report',
    ...catalogMeta('sales-report'),
    columns: [
      col('orderNumber', 'Order #', 'رقم الطلب', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('subtotal', 'Subtotal', 'المجموع', { sortable: true, className: 'text-end' }),
      col('shippingFee', 'Shipping', 'الشحن', { sortable: true, className: 'text-end' }),
      col('total', 'Total', 'الإجمالي', { sortable: true, className: 'text-end' }),
      col('currency', 'Currency', 'العملة'),
      col('paymentMethod', 'Payment', 'الدفع', { sortable: true }),
      col('deliveredAt', 'Delivered', 'تاريخ التسليم', { sortable: true }),
    ],
    filterKeys: ['client', 'dateRange'],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'client',
    chartValueKey: 'total',
    exportFileName: 'sales-report',
    serverSide: true,
  },
  {
    id: 'returns-report',
    ...catalogMeta('returns-report'),
    columns: [
      col('orderNumber', 'Order #', 'رقم الطلب', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('recipient', 'Recipient', 'المستلم', { sortable: true }),
      col('returnedAt', 'Returned', 'تاريخ الإرجاع', { sortable: true }),
      col('codAmount', 'COD amount', 'مبلغ COD', { sortable: true, className: 'text-end' }),
      col('paymentMethod', 'Payment', 'الدفع', { sortable: true }),
    ],
    filterKeys: ['client', 'dateRange'],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'client',
    chartValueKey: 'codAmount',
    exportFileName: 'returns-report',
    serverSide: true,
  },
  {
    id: 'delivery-report',
    ...catalogMeta('delivery-report'),
    columns: [
      col('orderNumber', 'Order #', 'رقم الطلب', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('status', 'Status', 'الحالة', { sortable: true }),
      col('carrier', 'Carrier', 'الناقل', { sortable: true }),
      col('trackingNumber', 'Tracking', 'التتبع', { sortable: true }),
      col('city', 'City', 'المدينة', { sortable: true }),
      col('outForDeliveryAt', 'Out for delivery', 'خارج للتسليم', { sortable: true }),
      col('deliveredAt', 'Delivered', 'تم التسليم', { sortable: true }),
    ],
    filterKeys: ['client', 'dateRange', 'status'],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'status',
    chartValueKey: 'total',
    exportFileName: 'delivery-report',
    serverSide: true,
  },
  {
    id: 'allocation-report',
    ...catalogMeta('allocation-report'),
    columns: [
      col('orderNumber', 'Order #', 'رقم الطلب', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('orderStatus', 'Order status', 'حالة الطلب', { sortable: true }),
      col('allocationStatus', 'Allocation', 'التخصيص', { sortable: true }),
      col('reservationCount', 'Reservations', 'الحجوزات', { sortable: true, className: 'text-end' }),
      col('allocatedAt', 'Allocated', 'تاريخ التخصيص', { sortable: true }),
    ],
    filterKeys: ['client', 'dateRange', 'status'],
    statusOptions: ALLOCATION_STATUS,
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'allocationStatus',
    chartValueKey: 'reservationCount',
    exportFileName: 'allocation-report',
    serverSide: true,
  },
  {
    id: 'inventory-reserved',
    ...catalogMeta('inventory-reserved'),
    columns: [
      col('orderNumber', 'Order #', 'رقم الطلب', { sortable: true }),
      col('client', 'Client', 'العميل', { sortable: true }),
      col('sku', 'SKU', 'رمز الصنف', { sortable: true }),
      col('product', 'Product', 'المنتج', { sortable: true }),
      col('location', 'Location', 'الموقع', { sortable: true }),
      col('lot', 'Lot', 'الدفعة'),
      col('quantity', 'Qty', 'الكمية', { sortable: true, className: 'text-end' }),
      col('status', 'Status', 'الحالة', { sortable: true }),
      col('createdAt', 'Created', 'تاريخ الإنشاء', { sortable: true }),
    ],
    filterKeys: ['client', 'sku'],
    defaultView: 'table',
    supportedViews: ['table', 'graph', 'pivot'],
    defaultChartKind: 'bar',
    chartLabelKey: 'client',
    chartValueKey: 'quantity',
    exportFileName: 'inventory-reserved',
    serverSide: true,
  },
];

export const DEFAULT_REPORT_ID = REPORT_REGISTRY[0]!.id;

export function getReportById(id: string): ReportDefinition | undefined {
  return REPORT_REGISTRY.find((r) => r.id === id);
}
