/** Must match `backend/src/modules/realtime/realtime.events.ts`. */
export const RealtimeEvents = {
  INBOUND_ORDER_CREATED: 'order.inbound.created',
  INBOUND_ORDER_UPDATED: 'order.inbound.updated',
  OUTBOUND_ORDER_CREATED: 'order.outbound.created',
  OUTBOUND_ORDER_UPDATED: 'order.outbound.updated',
  TASK_UPDATED: 'task.updated',
  INVENTORY_CHANGED: 'inventory.changed',
  PRODUCT_CREATED: 'product.created',
  PRODUCT_UPDATED: 'product.updated',
  PRODUCT_ARCHIVED: 'product.archived',
  PRODUCT_DELETED: 'product.deleted',
  RETURN_CREATED: 'return.created',
  RETURN_UPDATED: 'return.updated',
  RETURN_CONFIRMED: 'return.confirmed',
  RETURN_COMPLETED: 'return.completed',
  NOTIFICATION_CREATED: 'notification.created',
  NOTIFICATION_READ: 'notification.read',
  NOTIFICATION_DELETED: 'notification.deleted',
  OMS_ORDER_EVENT: 'oms.order.event',
  OMS_RETURN_EVENT: 'oms.return.event',
  COMPANY_LIFECYCLE_CHANGED: 'company.lifecycle.changed',
  BILLING_RESTRICTION_CHANGED: 'billing.restriction.changed',
  COD_UPDATED: 'cod.updated',
  INVOICE_UPDATED: 'invoice.updated',
  PLAN_UPDATED: 'plan.updated',
  AUTH_SESSION_CHANGED: 'auth.session.changed',
  SYSTEM_VERSION: 'system.version',
} as const;
