export {
  MODAL_CANCEL_BUTTON_CLASS as ADJUSTMENT_CANCEL_BUTTON_CLASS,
  MODAL_PRIMARY_BUTTON_CLASS as ADJUSTMENT_PRIMARY_BUTTON_CLASS,
  MODAL_PRIMARY_BUTTON_CLASS as INTERNAL_TRANSFER_PRIMARY_BUTTON_CLASS,
} from '../../lib/modal-button-styles';
